package com.renren.pub58.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCarReleaseAutoParmCode<M extends BaseCarReleaseAutoParmCode<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPlatformCode(java.lang.String platformCode) {
		set("platform_code", platformCode);
		return (M)this;
	}
	
	public java.lang.String getPlatformCode() {
		return getStr("platform_code");
	}

	public M setParamCode(java.lang.String paramCode) {
		set("param_code", paramCode);
		return (M)this;
	}
	
	public java.lang.String getParamCode() {
		return getStr("param_code");
	}

	public M setParamName(java.lang.String paramName) {
		set("param_name", paramName);
		return (M)this;
	}
	
	public java.lang.String getParamName() {
		return getStr("param_name");
	}

	public M setParamValue(java.lang.String paramValue) {
		set("param_value", paramValue);
		return (M)this;
	}
	
	public java.lang.String getParamValue() {
		return getStr("param_value");
	}

	public M setParamText(java.lang.String paramText) {
		set("param_text", paramText);
		return (M)this;
	}
	
	public java.lang.String getParamText() {
		return getStr("param_text");
	}

	public M setMatchSourceCode(java.lang.String matchSourceCode) {
		set("match_source_code", matchSourceCode);
		return (M)this;
	}
	
	public java.lang.String getMatchSourceCode() {
		return getStr("match_source_code");
	}

	public M setMatchSourceValue(java.lang.String matchSourceValue) {
		set("match_source_value", matchSourceValue);
		return (M)this;
	}
	
	public java.lang.String getMatchSourceValue() {
		return getStr("match_source_value");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
