package com.newcitysoft.crawl.pub58.model;

import com.newcitysoft.crawl.pub58.model.base.BaseCarReleaseAutoParmCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarReleaseAutoParmCode extends BaseCarReleaseAutoParmCode<CarReleaseAutoParmCode> {
	public static final CarReleaseAutoParmCode dao = new CarReleaseAutoParmCode().dao();
}
